[versions]
agp = "9.0.1"
constraintlayout = "2.2.1"
appcompat = "1.7.1"
material = "1.14.0-alpha09" # 1.14.0-alpha09


[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }